Release/0.0.1
nizepart/rest-go pull request #6
Opened 2024-04-10 21:03 UTC by nizepart

for teacher's review

2024-04-15 19:30 UTC, Serelllka requested changes

2024-04-15 19:30 UTC, Serelllka commented on Dockerfile
> +RUN apk update && apk add postgresql-client curl tzdata
Накатывать миграции в Dockerfile это не очень

2024-04-15 19:30 UTC, Serelllka commented on internal/app/apiserver/apiserver.go
> +	"database/sql"
отсортировать импорты можно

2024-04-15 19:30 UTC, Serelllka commented on internal/app/apiserver/emailhandlers.go
> +	type request struct {
я бы вынес это в отдельный файл model, в целом понимаю задумку, чтобы не плодить множество структур
можно оставить и так, но я бы вынес все-таки

2024-04-20 11:14 UTC, nizepart commented on Dockerfile
> +RUN apk update && apk add postgresql-client curl tzdata
Обсудили на консультации

2024-04-20 11:43 UTC, nizepart commented on internal/app/apiserver/emailhandlers.go
> +	type request struct {
Начал использовать существующие структуры без их дублирования. Пример: 
![image](https://github.com/nizepart/rest-go/assets/55020360/abbce4f3-8dd8-437f-a5a9-502b93199bce)

2024-05-23 08:42 UTC, merged